FROM python:3.9-slim

WORKDIR /app

COPY requirements_rastreamento.txt .

RUN pip install --no-cache-dir -r requirements_rastreamento.txt

COPY rastreamento_api.py .

EXPOSE 5001

CMD ["python", "rastreamento_api.py"]